pipeline {
    agent any

    stages {

        stage('Clone Code') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/main']],
                    userRemoteConfigs: [[
                        url: 'https://github.com/yuvichaudharybtech2023-spec/devops-finall'
                    ]]
                ])
            }
        }

        stage('Build') {
            steps {
                bat 'echo Building Feedback Project...'
            }
        }

        stage('List Files') {
            steps {
                bat 'dir'
            }
        }

        stage('Test') {
            steps {
                bat 'echo Running Tests...'
            }
        }

        stage('Deploy') {
            steps {
                bat 'echo Deploying Project...'
            }
        }
    }
}
